
openapi: "3.0.0"
info: 
  title: T-shirt store API
  description: First e-com app with help of lco
  version: 1.1.0
  contact:
    email: vaibhvmishra173@gmail.com

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost - secures
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost - secures
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns greet message from lco
      responses: 
        200:
          description: all good successs
          content:
            application/json:
              schema:
                type: string
                examply: "mystring"
        400:
          description: bad request
        500:
          description: internal server error