openapi: 3.0.0
info:
  title: Social app
  description: First Social app with help of lco
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of app
  - url: https://localhost:4000/api/v1
    description: dummy url api it doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /ig:
    get: 
      summary: returns username,followers and follows
      responses: 
        '200': # status code
          description: return's an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  follow:
                    type: string
    post: 
      summary: returns username,followers and follows
      responses: 
        '200': # status code
          description: return's an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  follow:
                    type: string
  /{token}:
    get: 
      summary: returns whatever in parameter
      parameters:
        - name: token
          default: 5
          in : path
          schema: 
            type: string
      responses: 
        '200': # status code
          description: return's an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  params:
                    type: string
